/** @type {import('tailwindcss').Config} */
import daisy from "daisyui";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      coloro: {
        "primary-100": "#f0f4fd",
        "primary-200": "#d9e2f8",
        "primary-300": "#a6c1f4",
        "primary-400": "#5985eb",
        "primary-500": "#3d5afe",
        "primary-600": "#3d5afe",
        "primary-700": "#3d5afe",
        "primary-800": "#3d5afe",
        "primary-900": "#3d5afe",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        open: ["Open Sans", "sans-serif"],
        popins: ["Poppins", "sans-serif"],
      },
    },
  },
  plugins: [daisy],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
    base: true,
    styled: true,
    utils: true,
  },
};
